spring:
  application:
    name: ${APP_NAME:gacha-service}
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:gacha_system_dev}?useSSL=${DB_USE_SSL:false}&serverTimezone=${DB_TIMEZONE:UTC}&characterEncoding=${DB_ENCODING:utf-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: ${JPA_DIALECT:org.hibernate.dialect.MySQLDialect}
        default_storage_engine: innodb

server:
  port: 8083

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.cheng.gacha: ${LOG_LEVEL_GACHA:DEBUG}
    com.cheng.common: ${LOG_LEVEL_COMMON:DEBUG}
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:DEBUG}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE_SQL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
